import type { Metadata } from 'next';
import { Inter, Readex_Pro } from 'next/font/google';
import '../globals.css';
import Navbar from '@/components/shared/Navbar';
import { Toaster } from '@/components/ui/toaster';
import { UserProvider } from '../context/UserContext';
import QueryProvider from '@/components/shared/QueryProvider';
import Footer from '@/components/shared/Footer';
import { VideoAnalysisProvider } from '../context/VideoAnalysisContext';

const inter = Readex_Pro({ subsets: ['arabic'] });

export const metadata: Metadata = {
  title: 'VisionAI Chrono ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <VideoAnalysisProvider>
            <QueryProvider>
              <main className="sticky top-0 z-50">
                <Navbar />
              </main>
              <div className="">{children}</div>
              {/* <Footer /> */}
            </QueryProvider>
          </VideoAnalysisProvider>
        </UserProvider>
        <Toaster />
      </body>
    </html>
  );
}
